### ISSUE TITLE
Send control characters?

### ISSUE THREAD

**Issue by egradman-red6ar** [samharju/yeet.nvim#2]
This plugin is *excellent* and will save me many thousands of keystrokes.  Thank you.

Would it be possible to send control sequences to the terminal on yeet?  I often test software that requires a control-c before being re-run.  (Perhaps by allowing me to add `<C-c>` to the string I type into the yeet command box?  But realistically, just a "send control-c before yeet" option in conf would be awesome.)

**Comment by samharju** [comment]
Thanks, it has saved me a million keystrokes and a thousand heartaches.

That should not be too complicated to add, I'll take a look at it next week.

**Comment by samharju** [comment]
It took a while, but C-c is now supported in v1.1.0. Take it for a test drive and let me know what you think!
