### ISSUE TITLE
Not working with Packer

### ISSUE THREAD

**Issue by rocktimsaikia** [samharju/yeet.nvim#4]
Running `Yeet` results in the command not being recognized by vim.

Packer settings:
```lua
    use({
        "samharju/yeet.nvim",
        requires = {
            "stevearc/dressing.nvim", -- optional, provides sane UX
        },
        tag = "*", -- update only on releases
        cmd = "Yeet",
        config = function()
            require("yeet").setup({})
        end,
    })
```

Error:
![Screenshot from 2024-09-08 23-31-02](https://github.com/user-attachments/assets/71f87944-0dce-406e-9906-d62b1bea144b)

**Comment by samharju** [comment]
Thanks for the report. I had bricked the user command without any arguments. Can't reproduce anymore with latest commit:
https://github.com/samharju/yeet.nvim/commit/f3f43b6a04c53b5c151d27f1e3f11f2a2d186c1d

Tried with this setup:

```lua
vim.cmd([[packadd packer.nvim]])

return require("packer").startup(function(use)
    use("wbthomason/packer.nvim")

    use({
        "samharju/yeet.nvim",
        requires = {
            "stevearc/dressing.nvim", -- optional, provides sane UX
        },
        cmd = "Yeet",
        config = function()
            require("yeet").setup({})
        end,
    })
end)
```

```
:PackerSync
:Yeet
```

If it fixes it for you, I'll push it out as 1.2.1.

**Comment by rocktimsaikia** [comment]
Yeah. It is working now after pulling the latest commit. Thanks. 
Nice tool btw. Discovered via a Reddit comment.

**Comment by samharju** [comment]
Pushed it out as v1.2.1.

And thanks, happy to help.
