### ISSUE TITLE
Indentation lost when using yeet in windows terminal

### ISSUE THREAD

**Issue by aris-mav** [samharju/yeet.nvim#5]
I really like the plugin, however, there seems to be an issue with using it on a windows terminal.

In linux (wsl-debian in my case), the yeeted text retains indentation, as shown below:
https://github.com/user-attachments/assets/aa222087-30e9-4dfb-97a4-3b4c881cf59e

But in windows that's not the case:
https://github.com/user-attachments/assets/2e780b12-494e-4f08-a142-90476619c08d

Note that in both cases, the text is sent to the repl but it's not evaluated, but perhaps that's due to my configuration?

My lazy config looks as follows:
```
return {
    "samharju/yeet.nvim",

    version = "*", -- use the latest release, remove for master
    cmd = "Yeet",
    opts = {
        -- Send <CR> to channel after command for immediate execution.
        yeet_and_run = true,
        -- Send C-c before execution
        interrupt_before_yeet = false,
        -- Send 'clear<CR>' to channel before command for clean output.
        clear_before_yeet = false,
        -- Enable notify for yeets. Success notifications may be a little
        -- too much if you are using noice.nvim or fidget.nvim
        notify_on_success = false,
        -- Print warning if pane list could not be fetched, e.g. tmux not running.
        warn_tmux_not_running = false,
    },
    keys = {

        -- Yeet visual selection. Useful sending core to a repl or running multiple commands.
        {
            "<cr>",
            function()
                require("yeet").execute_selection(
                {yeet_and_run = true, clear_before_yeet = false, notify_on_success = false }
                )
            end,
            mode = { "v" },
        },

        -- Yeet current line
        {
            "<cr>",
            function()
                require("yeet").execute(
                vim.api.nvim_get_current_line(),
                {yeet_and_run = true, clear_before_yeet = false, notify_on_success = false }
                )
            end,
            mode = { "n" },
        },
    }
}
```

**Comment by samharju** [comment]
Thanks for solid bug report, I'll check these soon.

**Comment by aris-mav** [comment]
Awesome, thanks! 
One more detail I forgot to mention: looking at [this file](https://github.com/samharju/yeet.nvim/blob/master/lua/yeet/selection.lua), it seems the visual selection option only works for full lines. Would it be sensible to modify it so that parts of lines could also be yeeted?

**Comment by samharju** [comment]
I have been running with these changes for about a week with a couple of other changes.

Charwise selection: 4b3e6628e46fbd3207e37832fe82027efda34412

I'm probably going to add a flag for disabling or enabling the charwise selection, as I already am used to reckless range game.

Windows newlines: c2e34247957e0772737ca487282b8531ca11e196

You can test these by running from master, remove the version lock from plugin setup.

**Comment by aris-mav** [comment]
Amazing, works like a charm. 
Thank you so much! 
I believe we can close the issue.

**Comment by samharju** [comment]
Thanks, I have some cleaning to be done in the readme before a release, so keep using the master branch for a while.
